# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
     vb.memory = "4096"
     vb.cpus = 4
   end
   
   config.vm.provision "shell", inline: <<-SHELL
     curl -fsSL https://get.docker.com -o get-docker.sh
     sudo sh get-docker.sh
     sudo usermod -aG docker vagrant
     su - vagrant     
     curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
     chmod +x minikube
     sudo mkdir -p /usr/local/bin/
     sudo install minikube /usr/local/bin/
     echo "installed minikube"
     sudo yum install -y conntrack
     sudo yum install -y kubernetes-client
     systemctl start docker
     systemctl enable docker
   SHELL
end
